[projects."/Users/xuwentao/Projects/github/patent-platform"]
trust_level = "trusted"

[projects."/Users/xuwentao/Projects/github/volcano"]
trust_level = "trusted"

[projects."/Users/xuwentao/.codex"]
trust_level = "trusted"

[tui]
terminal_title = []

status_line = ["model-with-reasoning", "context-remaining", "current-dir", "context-used", "five-hour-limit"]

[features]
codex_hooks = true

[plugins."github@openai-curated"]
enabled = true
